/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hesfb_disbursment;

/**
 *
 * @author Namara Rauben
 */
public class GUARANTOR_DETAILS extends javax.swing.JFrame {

    /**
     * Creates new form GUARANTOR_DETAILS
     */
    public GUARANTOR_DETAILS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        GUARANTOR_DETAILS = new javax.swing.JLabel();
        GUARANTOR_ID = new javax.swing.JLabel();
        ADDRESS_ID = new javax.swing.JLabel();
        GUARANTOR_NAME = new javax.swing.JLabel();
        PHONE = new javax.swing.JLabel();
        SAVE = new javax.swing.JButton();
        PROCEED = new javax.swing.JButton();
        TF_ID = new javax.swing.JTextField();
        TF_ADDRESS = new javax.swing.JTextField();
        TR_NAME = new javax.swing.JTextField();
        TF_PHONE = new javax.swing.JTextField();
        btnexit = new javax.swing.JButton();
        PHONE1 = new javax.swing.JLabel();
        PHONE2 = new javax.swing.JLabel();
        TF_PHONE1 = new javax.swing.JTextField();
        TF_PHONE2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        GUARANTOR_DETAILS.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        GUARANTOR_DETAILS.setText("GUARANTOR DETAILS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(GUARANTOR_DETAILS, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GUARANTOR_DETAILS)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GUARANTOR_ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GUARANTOR_ID.setText("GUARANTOR ID");

        ADDRESS_ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ADDRESS_ID.setText("NAME");

        GUARANTOR_NAME.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GUARANTOR_NAME.setText("EMAIL");

        PHONE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PHONE.setText("CONTACT");

        SAVE.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SAVE.setText("SAVE");
        SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVEActionPerformed(evt);
            }
        });

        PROCEED.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        PROCEED.setText("PROCCED");
        PROCEED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PROCEEDActionPerformed(evt);
            }
        });

        TF_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_IDActionPerformed(evt);
            }
        });

        TF_ADDRESS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_ADDRESSActionPerformed(evt);
            }
        });

        TR_NAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TR_NAMEActionPerformed(evt);
            }
        });

        TF_PHONE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_PHONEActionPerformed(evt);
            }
        });

        btnexit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnexit.setText("EXIT");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        PHONE1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PHONE1.setText("PROFESSIONAL");

        PHONE2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PHONE2.setText("OCCUPATION");

        TF_PHONE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_PHONE1ActionPerformed(evt);
            }
        });

        TF_PHONE2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_PHONE2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(GUARANTOR_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TF_PHONE2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                                    .addComponent(TR_NAME, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TF_ADDRESS, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TF_ID, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TF_PHONE, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TF_PHONE1)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GUARANTOR_NAME)
                                    .addComponent(PHONE)
                                    .addComponent(ADDRESS_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PHONE2)
                                    .addComponent(PHONE1))
                                .addGap(23, 23, 23)
                                .addComponent(btnexit)
                                .addGap(50, 50, 50)
                                .addComponent(SAVE)
                                .addGap(42, 42, 42)
                                .addComponent(PROCEED)))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(GUARANTOR_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TF_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TF_ADDRESS, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ADDRESS_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(TR_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(GUARANTOR_NAME))
                        .addGap(32, 32, 32)
                        .addComponent(TF_PHONE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PHONE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PHONE1)
                    .addComponent(TF_PHONE2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PHONE2)
                    .addComponent(TF_PHONE1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SAVE, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnexit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PROCEED, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SAVEActionPerformed

    private void TR_NAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TR_NAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TR_NAMEActionPerformed

    private void TF_PHONEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_PHONEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_PHONEActionPerformed

    private void PROCEEDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PROCEEDActionPerformed
        // TODO add your handling code here:
        new GUARANTOR_ADDRESS().setVisible(true);
        dispose();
    }//GEN-LAST:event_PROCEEDActionPerformed

    private void TF_ADDRESSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_ADDRESSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_ADDRESSActionPerformed

    private void TF_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_IDActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnexitActionPerformed

    private void TF_PHONE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_PHONE1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_PHONE1ActionPerformed

    private void TF_PHONE2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_PHONE2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_PHONE2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUARANTOR_DETAILS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUARANTOR_DETAILS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUARANTOR_DETAILS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUARANTOR_DETAILS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUARANTOR_DETAILS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ADDRESS_ID;
    private javax.swing.JLabel GUARANTOR_DETAILS;
    private javax.swing.JLabel GUARANTOR_ID;
    private javax.swing.JLabel GUARANTOR_NAME;
    private javax.swing.JLabel PHONE;
    private javax.swing.JLabel PHONE1;
    private javax.swing.JLabel PHONE2;
    private javax.swing.JButton PROCEED;
    private javax.swing.JButton SAVE;
    private javax.swing.JTextField TF_ADDRESS;
    private javax.swing.JTextField TF_ID;
    private javax.swing.JTextField TF_PHONE;
    private javax.swing.JTextField TF_PHONE1;
    private javax.swing.JTextField TF_PHONE2;
    private javax.swing.JTextField TR_NAME;
    private javax.swing.JButton btnexit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
